language: node_js
node_js:
  - 8
  - 9
  - node
cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV=development

script:
  - echo "Running tests against $(node -v) ...
  - yarn test
