language: node_js
node_js:
  - 8
  - 10
  - node
cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn install
  - yarn build
  - yarn docs

script:
  - yarn test

after_success:
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: '$NPM_EMAIL'
    api_key: $NPM_TOKEN
    on:
      tags: true
