language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - echo "Running tests against $(node -v) ...
  - yarn test

before_deploy:
  - yarn build

after_success:
  - yarn typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: '{YOURLIB}-*.tgz'
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: '$NPM_EMAIL'
    api_key: $NPM_TOKEN
    on:
      tags: true
